#!/bin/bash
input="insert-domains-here"
echo "---------------Verificação Iniciada-----------------"
while IFS= read -r line
do
echo ""
echo ""
echo ""
echo "---------------------------------------------------------------------"
echo "Analisando $line"
echo "---------------------------------------------------------------------"
echo "                  [RESULTADOS]"
WEBSITEHTTP=$(echo "http://$line")
WEBSITEHTTPS=$(echo "https://$line")
HTTP=$(echo | curl -sL -w "%{http_code}\\n" $WEBSITEHTTP -o /dev/null)
HTTPS=$(echo | curl -sL -w "%{http_code}\\n" $WEBSITEHTTPS -o /dev/null)
CODE="200"
if [[ "$HTTP" == "$CODE" ]];
then
        echo "HTTP identificado"
else
        echo ""
fi
if [[ "$HTTPS" == "$CODE" ]];
then
        echo "HTTPS identificado"
else
        echo ""
fi
echo ""
done <"$input"
